In [1]:
import pandas as pd
#opens a file dialog in the current folder (detailed)
from tkinter import filedialog as fd

In [2]:
filename = fd.askopenfilename() #select the input file from Advent
#opens the file and then reads the lines
StrtGuide=pd.read_csv(filename, sep=" ", header=None,names=['OppPlay','StratPlay'])
StrtGuide

     OppPlay StratPlay
0          B         Y
1          C         Z
2          C         Y
3          C         Y
4          A         X
...      ...       ...
2495       A         X
2496       B         Y
2497       B         Y
2498       C         Z
2499       B         Y

[2500 rows x 2 columns]

In [28]:
PlayPoints={'A':1,'B':2,'C':3,'X':1,'Y':2,'Z':3}
DrawDict={'A':'X','B':'Y','C':'Z'}
WinDict={'A':'Y', 'B':'Z', 'C':'X'}
NumOpp=[]
NumStrt=[]
for index in range(StrtGuide.shape[0]):
    NumOpp.append(PlayPoints[StrtGuide.iloc[index,0]])
    NumStrt.append(PlayPoints[StrtGuide.iloc[index,1]])
StrtGuide["NumOpp"]=NumOpp
StrtGuide["NumStrt"]=NumStrt
StrtGuide

     OppPlay StratPlay  NumOpp  NumStrt
0          B         Y       2        2
1          C         Z       3        3
2          C         Y       3        2
3          C         Y       3        2
4          A         X       1        1
...      ...       ...     ...      ...
2495       A         X       1        1
2496       B         Y       2        2
2497       B         Y       2        2
2498       C         Z       3        3
2499       B         Y       2        2

[2500 rows x 4 columns]

In [26]:
Basescore=sum(StrtGuide.iloc[:,3])
Winscore=0
for index in range(StrtGuide.shape[0]):
    if StrtGuide.iloc[index,2]<StrtGuide.iloc[index,3]:
        Winscore+=6
    elif StrtGuide.iloc[index,2]==StrtGuide.iloc[index,3]:
        Winscore+=3
print(Winscore,Basescore,Winscore+Basescore)

6537 5100 11637

In [39]:
test=[['A','Y'],['B','X'],['C','Z']]
test=pd.DataFrame(test,columns=['OppPlay','StratPlay'])
NumOpp=[]
NumStrt=[]
for index in range(test.shape[0]):
    NumOpp.append(PlayPoints[test.iloc[index,0]])
    NumStrt.append(PlayPoints[test.iloc[index,1]])
test["NumOpp"]=NumOpp
test["NumStrt"]=NumStrt
test

15

In [6]:
#Question 2: X Y Z is the strategy
PlayPoints={'A':1,'B':2,'C':3}
DrawDict={'A':'A','B':'B','C':'C'}
WinDict={'A':'B', 'B':'C', 'C':'A'}
LoseDict={'A':'C','B':'A','C':'B'}
baseScore=0
play=[]
for index in range(StrtGuide.shape[0]):
    if StrtGuide.iloc[index,1]=='X':
        baseScore+=0
        play.append(PlayPoints[LoseDict[StrtGuide.iloc[index,0]]])
    if StrtGuide.iloc[index,1]=='Y':
        baseScore+=3
        play.append(PlayPoints[DrawDict[StrtGuide.iloc[index,0]]])
    elif StrtGuide.iloc[index,1]=='Z':
        baseScore+=6
        play.append(PlayPoints[WinDict[StrtGuide.iloc[index,0]]])
baseScore+sum(play)

13022